apiVersion: v1
kind: Service
metadata:
  name: isoflow
  namespace: isoflow
  labels:
    app: isoflow
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: isoflow
  clusterIP: None
