apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources-pvc
  namespace: romm
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library-pvc
  namespace: romm
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets-pvc
  namespace: romm
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config-pvc
  namespace: romm
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
